---
title: "B cell"
output: html_document
date: "2024-12-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

``` {r}
#load Seurat obj! 
library(Seurat)
library(tidyverse)
seurat.obj<- readRDS("seurat.obj.final.RDS")
view(seurat.obj@meta.data)

#Dimplot ! 
umap<- DimPlot(seurat.obj, reduction = "umap", label = TRUE) +
  theme_classic() +
  NoLegend() + 
  theme(axis.title = element_text(size= 15, face = "bold"),
        axis.text = element_text(size = 14, face = "bold")) + 
  NoAxes()
umap
```


#subet B cell !!! 
 
``` {r}
seurat.obj.Bcell<- subset(seurat.obj, idents = c("19"))

#remove patients SA6 !! 
seurat.obj.Bcell<- subset(seurat.obj.Bcell, subset= orig.ident != "SA6")
view(seurat.obj.Bcell@meta.data)
DimPlot(seurat.obj.Bcell, reduction= "umap", label = TRUE) +
  theme_classic() +
  NoLegend()
```

# SCT/PCA 
``` {r}
#SCTransform
B.subcluster<- SCTransform(seurat.obj.Bcell)

#Run PCA
B.subcluster<- RunPCA(B.subcluster, verbose = FALSE)

saveRDS(cd4.subcluster, file = "cd4.subcluster.sct.pca.rds")  #save on 01/31/2024

#Elbow plot
T.subcluster<- read_rds("T.subcluster.sct.pca.rds")

ElbowPlot(B.subcluster, ndims = 50, reduction = "pca") +
  ggtitle("Number of principle component")  + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))

``` 
# Integration/clustering

``` {r}
library(harmony)
B.integration<- RunHarmony(B.subcluster,
                              group.by.vars = "orig.ident")
saveRDS(cd4.T.integration, file = "cd4.cell.harmony.rds")   #save on 01/31/2024
```


# PC= 10
``` {r}
B.pc10 <- FindNeighbors(B.integration, 
                                 reduction = "harmony", 
                               dims = 1:10)

B.pc10<- FindClusters(B.pc10 ,
                                 resolution = 0)

B.pc10<- RunUMAP(object = B.pc10,
                          reduction = "harmony",
                          dims = 1:10)

# umap plot 
DimPlot(B.pc10, reduction= "umap", label = FALSE, sizes.highlight = 10) +
  theme_classic() +
  NoLegend() + 
  theme(plot.title = element_text(hjust = 0.5, face = "bold"), 
        panel.grid = element_blank(),
        axis.text = element_text(face = "bold", size= 16), 
        axis.title = element_text(face = "bold", size= 18)) + 
  NoLegend() 
```  

# PC= 15
``` {r}
B.pc20 <- FindNeighbors(B.integration, 
                                 reduction = "harmony", 
                               dims = 1:20)

B.pc20<- FindClusters(B.pc20 ,
                                 resolution = 0)

B.pc20<- RunUMAP(object = B.pc15,
                          reduction = "harmony",
                          dims = 1:20)

# umap plot 
B.pc20<- read_rds("B.cell.rds")
#subset the first and second IA !!! 
firstsecondB<- subset(B.pc20, subset = type %in% c("First arthritis","Second arthritis")) 
bcell.umap<- DimPlot(firstsecondB, 
                     reduction= "umap", 
                     label = FALSE, 
                     sizes.highlight = 10,
                     pt.size = 2, 
                     group.by = "type") +
  theme(plot.title = element_blank(), 
        panel.grid = element_blank(),
        axis.text = element_text(face = "bold", size= 14), 
        axis.title = element_text(face = "bold", size= 16)) + 
  NoLegend()

#save bcell object
saveRDS(B.pc20, file = "B.cell.rds")

bcell.umap
```



#save high quality plot 
``` {r}
ggsave("umap.b.pdf", plot = bcell.umap, height=3, width = 3, units = "in", dpi = 300)

``` 


#Subset only first and second !!! 
``` {r}
Bcell.ici<- subset(B.pc20, subset = type %in% c("First arthritis", "Second arthritis"))
view(Bcell.ici@meta.data)
DefaultAssay(Bcell.ici)<- "RNA"
```

#genes 
``` {r}
genes <- c("CD19","IGHD", "IGHG1","IGHG2","PAX5", "HLA-DRB1", "CXCR5", "TNF", "CD27","CD1C", "ANXA2", 
           "POU2AF1", "S100A10")
``` 


``` {r}
bcell.dot_plot<- DotPlot(Bcell.ici, features = genes, cols = c("blue", "red"), dot.scale = 6, group.by = "type") + 
  theme_classic() +
  RotatedAxis() + 
  coord_flip() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size=15), 
        axis.title.y= element_blank(), 
        axis.text = element_text(size=12, face = "bold"), 
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(),
        legend.title = element_text(size= 14, face = "bold"), 
        legend.text = element_text(size= 14, face = "bold")) + 
  theme(legend.position = "none")
bcell.dot_plot
``` 

#Feature plot
``` {r}
ggsave("Bcell_markers.pdf", plot = bcell.dot_plot, height=2.7, width = 3, units = "in", dpi = 300)

``` 

#get B cell legend !!! 
``` {r}
bcell.dot_plot<- DotPlot(Bcell.ici, features = genes, cols = c("blue", "red"), dot.scale = 6, group.by = "type") + 
  theme_classic() +
  RotatedAxis() + 
  coord_flip() +
  theme(plot.title = element_text(hjust = 0.5, face = "bold", size=15), 
        axis.title.y= element_blank(), 
        axis.text = element_text(size=12, face = "bold"), 
        axis.text.x = element_blank(), 
        axis.title.x = element_blank(),
        legend.title = element_text(size= 14, face = "bold"), 
        legend.text = element_text(size= 14, face = "bold")) + 
  theme(legend.position = "right")
bcell.dot_plot




``` 
``` {r}
ggsave("Bcell_markers.legend.pdf", plot = bcell.dot_plot, height=4, width = 3, units = "in", dpi = 300)

``` 





