---
title: "SCtran_deep_filter"
output: html_document
date: "2023-11-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load the required library 
``` {r, warning= FALSE, fig.width= 6, fig.height= 6}
library(tidyverse)
library(Seurat)
library(patchwork)
library(sctransform)
library(glmGamPoi)
```

``` {r}
#read data of 164S !
A164S<- Read10X(data.dir = "164S")

#create seurat object
A164S<- CreateSeuratObject(counts = A164S, project = "164S", min.cells = 3, min.features = 200)
A164S
```

``` {r}
#add variable 
A164S$type= "First arthritis" 

#set percent MT
A164S.mt<- PercentageFeatureSet(A164S, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.164s<- VlnPlot(A164S.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.164s

#filter cells 
Filtered.cells.164s <- subset(A164S.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5500 & nCount_RNA>500 & nCount_RNA <25000 & percent.mt <15)

#plot filtered cells!  
Filtered.164s<- VlnPlot(Filtered.cells.164s, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.164s

#plot both
unfiltered.164s/Filtered.164s
```

``` {r}
#read data of 164S !
A164S2<- Read10X(data.dir = "164S2")

#create seurat object
A164S2<- CreateSeuratObject(counts = A164S2, project = "164S2", min.cells = 3, min.features = 200)
A164S2
```

``` {r}
#add variable 
A164S2$type= "Second arthritis" 

#set percent MT
A164S2.mt<- PercentageFeatureSet(A164S2, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.164S2<- VlnPlot(A164S2.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.164S2

#filter cells 
Filtered.cells.164S2 <- subset(A164S2.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <55000 & nCount_RNA>500 & nCount_RNA <20000 & percent.mt <15)

#plot filtered cells!  
Filtered.164S2<- VlnPlot(Filtered.cells.164S2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.164S2

#plot both
unfiltered.164S2/Filtered.164S2
```
``` {r}
#read data of 184S2 !
A184S2<- Read10X(data.dir = "184S2")

#create seurat object
A184S2<- CreateSeuratObject(counts = A184S2, project = "184S2", min.cells = 3, min.features = 200)
A184S2
```
``` {r}
#add variable 
A184S2$type= "First arthritis" 

#set percent MT
A184S2.mt<- PercentageFeatureSet(A184S2, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.184S2<- VlnPlot(A184S2.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.184S2

#filter cells 
Filtered.cells.184S2 <- subset(A184S2.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5000 & nCount_RNA>500 & nCount_RNA <23000 & percent.mt <15)

#plot filtered cells!  
Filtered.184S2<- VlnPlot(Filtered.cells.184S2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.184S2

#plot both
unfiltered.184S2/Filtered.184S2
```


``` {r}
#read data of 184S3 !
A184S3<- Read10X(data.dir = "184S3")

#create seurat object
A184S3<- CreateSeuratObject(counts = A184S3, project = "184S3", min.cells = 3, min.features = 200)
A184S3
```
``` {r}
#add variable 
A184S3$type= "Second arthritis" 

#set percent MT
A184S3.mt<- PercentageFeatureSet(A184S3, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.184S3<- VlnPlot(A184S3.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.184S3

#filter cells 
Filtered.cells.184S3 <- subset(A184S3.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5000 & nCount_RNA>500 & nCount_RNA <23000 & percent.mt <15)

#plot filtered cells!  
Filtered.184S3<- VlnPlot(Filtered.cells.184S3, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.184S3

#plot both
unfiltered.184S3/Filtered.184S3
```
``` {r}
#read data of 184S3 !
A218S<- Read10X(data.dir = "218S")

#create seurat object
A218S<- CreateSeuratObject(counts = A218S, project = "218S", min.cells = 3, min.features = 200)
A218S
```

``` {r}
#add variable 
A218S$type= "First arthritis" 

#set percent MT
A218S.mt<- PercentageFeatureSet(A218S, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.218S<- VlnPlot(A218S.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.218S

#filter cells 
Filtered.cells.218S <- subset(A218S.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5000 & nCount_RNA>500 & nCount_RNA <20000 & percent.mt <15)

#plot filtered cells!  
Filtered.218S<- VlnPlot(Filtered.cells.218S, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.218S

#plot both
unfiltered.218S/Filtered.218S
```


``` {r}
#read data of 184S3 !
A218S2<- Read10X(data.dir = "218S2")

#create seurat object
A218S2<- CreateSeuratObject(counts = A218S2, project = "218S2", min.cells = 3, min.features = 200)
A218S2
```
``` {r}
#add variable 
A218S2$type= "Second arthritis" 

#set percent MT
A218S2.mt<- PercentageFeatureSet(A218S2, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.218S2<- VlnPlot(A218S2.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.218S2

#filter cells 
Filtered.cells.218S2 <- subset(A218S2.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5000 & nCount_RNA>500 & nCount_RNA <20000 & percent.mt <15)

#plot filtered cells!  
Filtered.218S2<- VlnPlot(Filtered.cells.218S2, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.218S2

#plot both
unfiltered.218S2/Filtered.218S2
```

``` {r}
#read data of SA5 !
ASA5<- Read10X(data.dir = "SA5")

#create seurat object
ASA5<- CreateSeuratObject(counts = ASA5, project = "SA5", min.cells = 3, min.features = 200)
ASA5
```
``` {r}
#add variable 
ASA5$type= "Osteoarthritis" 

#set percent MT
ASA5.mt<- PercentageFeatureSet(ASA5, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.SA5<- VlnPlot(ASA5.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.SA5

#filter cells 
Filtered.cells.SA5 <- subset(ASA5.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <5500 & nCount_RNA>500 & nCount_RNA <25000 & percent.mt <15)

#plot filtered cells!  
Filtered.SA5<- VlnPlot(Filtered.cells.SA5, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.SA5

#plot both
unfiltered.SA5/Filtered.SA5
```

``` {r}
#read data of SA6 !
ASA6<- Read10X(data.dir = "SA6")

#create seurat object
ASA6<- CreateSeuratObject(counts = ASA6, project = "SA6", min.cells = 3, min.features = 200)
ASA6
```
``` {r}
#add variable 
ASA6$type= "Osteoarthritis" 

#set percent MT
ASA6.mt<- PercentageFeatureSet(ASA6, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.SA6<- VlnPlot(ASA6.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.SA6

#filter cells 
Filtered.cells.SA6 <- subset(ASA6.mt, subset = nFeature_RNA >500 & nFeature_RNA <7000
              & nCount_RNA>500 & nCount_RNA <48000 & percent.mt <15)

#plot filtered cells!  
Filtered.SA6<- VlnPlot(Filtered.cells.SA6, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.SA6

#plot both
unfiltered.SA6/Filtered.SA6
```



``` {r}
#read data of SA6 !
ASA7<- Read10X(data.dir = "SA7")

#create seurat object
ASA7<- CreateSeuratObject(counts = ASA7, project = "SA7", min.cells = 3, min.features = 200)
ASA7
```
``` {r}
#add variable 
ASA7$type= "Osteoarthritis" 

#set percent MT
ASA7.mt<- PercentageFeatureSet(ASA7, pattern = "^MT-", col.name = "percent.mt")

#plot unfiltered data 
unfiltered.SA7<- VlnPlot(ASA7.mt, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
unfiltered.SA7

#filter cells 
Filtered.cells.SA7 <- subset(ASA7.mt, subset = nFeature_RNA >500 
              & nFeature_RNA <6900
              & nCount_RNA>500 & nCount_RNA <37000 & percent.mt <15)

#plot filtered cells!  
Filtered.SA7<- VlnPlot(Filtered.cells.SA7, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filtered.SA7

#plot both
unfiltered.SA7/Filtered.SA7
```





# Merge Seurat Object and plot unfiltered cells
``` {r, fig.width= 9, fig.height= 5}
#merge objects
Arthritis.merge<- merge(Filtered.cells.164s, y=c(Filtered.cells.164S2, Filtered.cells.184S2, Filtered.cells.184S3, Filtered.cells.218S,
                                                 Filtered.cells.218S2, Filtered.cells.SA5, Filtered.cells.SA6, Filtered.cells.SA7))

#plot unfiltered data 
Filter.all.sample<- VlnPlot(Arthritis.merge, features = c("nFeature_RNA", "nCount_RNA", "percent.mt"), ncol = 3)
Filter.all.sample
```


# Normalize cell using seurat pipeline

``` {r}
Arthritis<- NormalizeData(Arthritis.merge)
Arthritis<- FindVariableFeatures(Arthritis, selection.method = "vst", nfeatures = 2000, verbose = FALSE)
Arthritis<- ScaleData(Normalized.164s, vars.to.regress = c("nFeature_RNA", "percent_mt"), verbose = FALSE)
Arthritis <- RunPCA(Arthritis, seed.use = 12345, verbose = FALSE)
``` 


# Perform dimensionality reduction by PCA and plot PC components
``` {r}
#Elbow plot
ElbowPlot(Arthritis, ndims = 50,reduction = "pca") +
  ggtitle("Number of principle component")  + 
  theme_minimal() +
  theme(plot.title = element_text(hjust = 0.5))
``` 

# Cell cycle scoring 
``` {r}
s.genes <- cc.genes$s.genes
g2m.genes <- cc.genes$g2m.genes
Arthritis<- CellCycleScoring(Arthritis, s.features = s.genes, g2m.features = g2m.genes, set.ident = TRUE)
head(Arthritis[[]])

Arthritis<- RunPCA(Arthritis, features = c(s.genes, g2m.genes))
DimPlot(Arthritis, reduction = "umap")
``` 
#Regress out cell cycle scores during data scaling

``` {r}
Arthritis <- ScaleData(Arthritis, vars.to.regress = c("S.Score", "G2M.Score"), features = rownames(Arthritis))

# the variable genes no longer returns components associated with cell cycle
Arthritis <- RunPCA(marrow, features = VariableFeatures(marrow), nfeatures.print = 10)
``` 

# Integration using harmony
``` {r}
library(harmony)
set.seed(12345)
Arthritis<- RunHarmony(Arthritis, group.by.vars = "orig.ident")
```


``` {r, fig.width= 6, fig.height= 4}
Arthritis<- RunUMAP(object = Arthritis,
                          reduction = "harmony",
                          dims = 1:40)

Arthritis<- FindNeighbors(object = Arthritis, reduction="harmony", dims = 1:40)
Arthritis<- FindClusters(object = Arthritis, resolution = 0.6, random.seed = 12345)
DimPlot(Arthritis, label= TRUE) +
  theme_minimal() +
  NoLegend()
``` 


``` {r, fig.width= 9, fig.height= 5}
FeaturePlot(Arthritis, features = c("CD3E", "CD8A", "CD4", "FOXP3"), pt.size = 0.2,
    ncol = 2)
``` 

# Investigate gene that are differently expressed
``` {r, fig.width= 7, fig.height= 4, warning= FALSE}
#Data normalization 
set.seed(12345)
All_arthritis_normal <- NormalizeData(Arthritis.merge) 
All_arthritis_normal <- FindVariableFeatures(All_arthritis_normal) 

#feature scaling !
All_arthritis_normal <- ScaleData(All_arthritis_normal, vars.to.regress = c("nFeature_RNA", "percent_mito"), verbose = FALSE) 
All_arthritis_normal <- RunPCA(All_arthritis_normal, seed.use = 12345,verbose = FALSE)

#Plot PC components ! 
ElbowPlot(All_arthritis_normal, ndims = 50,reduction = "pca") +
  ggtitle("Number of principle component")  + 
  theme(plot.title = element_text(hjust = 0.5)) +
  theme_minimal()
```
# Integration using Harmony
``` {r, fig.width= 5, fig.height= 4}
library(harmony)
set.seed(12345)
All_arthritis_integration<- RunHarmony(All_arthritis_normal, group.by.vars = "orig.ident")
All_arthritis_integration <- RunUMAP(object = All_arthritis_integration,
                          reduction = "harmony",
                          dims = 1:40)

All_arthritis_integration <- FindNeighbors(object = All_arthritis_integration, reduction="harmony", dims = 1:40)
All_arthritis_integration <- FindClusters(object = All_arthritis_integration, resolution = 0.6, random.seed = 12345)
DimPlot(All_arthritis_integration) +
  theme_minimal() +
  NoLegend()
``` 
``` {r, fig.width= 9, fig.height= 5}
FeaturePlot(All_arthritis_integration, features = c("CD3E", "CD8A", "CD4", "FOXP3"), pt.size = 0.2,
    ncol = 2)
``` 