---
title: "Monocle3"
output: html_document
date: "2024-02-22"
---

# Annotate T cell subclusters! 

``` {r}
#load Seurat obj! 
library(Seurat)
library(monocle3)
library(SeuratWrappers)

#load Seurat obj! 
seurat.obj.T<- readRDS("umap.obj.pc15.rds")

#Dimplot ! 
DimPlot(seurat.obj.T, reduction = "umap", label = TRUE) +
  theme_minimal() +
  NoLegend()
``` 
# Annotation ! 
*0= Th17 like cell*
*1= CD8 effector*
*2= ILC*
*3= Treg*
*4= CD4 Tcm* 
*5= CD8 Tem* 
*6= PD-1hi CXCL13hi CD4+*
*7= Effector CD8* 
*8= Th1-like*
*9= Cytotoxic T*
*10= Recently activated CD4*
*11= Treg*
*12= NKG7+ CD8+ T cells*
*13= NKT*
*14= CD8 Trm*
*15= MAIT*
*16= Cycling T*
*17= KLRB1hi CD8 Tem*
*18= mixed CD4*

# Perform Monocle3 
# Seurat Wrapper
``` {r}
# 2. Convert to Seurat object to cell_data_set object ------
cds <- as.cell_data_set(seurat.obj.T, group.by='ident') # SeuratWrappers
DefaultAssay(seurat.obj.T)
``` 

# Learn the trajectory graph
``` {r}
cds <- cluster_cells(cds, resolution = 1e-5)  #fit with Seurat ! 

plot_cells(cds, color_cells_by = 'ident', 
           label_groups_by_cluster = FALSE,
           group_label_size = 5) +
  theme(legend.position = "right")  # already run and get the same graph! 
```

# 3. trajectory analysis
``` {r}
cds <- learn_graph(cds, use_partition = FALSE)

# plot
cd<- plot_cells(cds, color_cells_by = 'ident', 
           label_groups_by_cluster = FALSE,
           group_label_size = 5) +
  theme_minimal() +
  theme(legend.position = "none")
```
 
# Order the cells by pseudotime 
``` {R}
cds <- order_cells(cds)

#plot_cells in pseudotime
trjec<- plot_cells(cds, color_cells_by = 'pseudotime', 
           label_branch_points = FALSE, label_leaves = FALSE) + 
  theme_minimal()
``` 

``` {r}
sessionInfo()
``` 




